### ISSUE TITLE
[FEAT] 상품 상세 페이지

### ISSUE THREAD

**Issue by hwb0218** [hwb0218/look-so-p#11]
## Description

상품 상세 페이지를 구현합니다.

</br>

## To-do

- [x] 상품을 클릭하면 보여지는 상세 페이지 UI
- [x] 상세 페이지 제품명, 사진, 가격, 남은 수량 정보 출력
- [x] 동일 카테고리 추천 상품  페이지 하단 배치

</br>

## 레퍼런스

</br>
