### ISSUE TITLE
[FEAT] 리액트 앱 렌더링 최적화

### ISSUE THREAD

**Issue by hwb0218** [hwb0218/look-so-p#29]
## Description

React DevTools 프로파일러를 사용한 컴포넌트 렌더링 성능 분석등을 통해 렌더링 최적화합니다.

</br>

## To-do  
- [x] 리렌더링을 야기 할 수 있는 함수 useCallback으로 캐싱하기.
- [ ] Cumputation cost가 큰 계산이 있다면 (필터 리스트 등) 리렌더링 사이의 계산 결과를 useMemo로 캐싱하기.
- [x] React.memo로 불필요한 리랜더링일 일어 날 수 있는 부분을 찾아 컴포넌트 메모화하기.

</br>

## 레퍼런스

</br>
