### ISSUE TITLE
[FEAT] 고급 필터링 및 검색 기능

### ISSUE THREAD

**Issue by hwb0218** [hwb0218/look-so-p#31]
## Description

- 고급 필터링 및 검색 기능을 구현합니다.

</br>

## To-do

- [x] 사용자가 다양한 기준으로 상품을 검색하는 기능을 구현합니다. 
- [ ] 필터링할 수 있는 기능 태그 시스템, 가격 범위 선택기, 다중 선택 필터 등을 구현합니다.
- [ ] 검색 결과 페이지에서 상품의 다양한 뷰(리스트 뷰, 그리드 뷰)를 전환할 수 있는 기능을 제공합니다.

</br>

## 레퍼런스

</br>
