### ISSUE TITLE
[FEAT] 판매자 등록 상품 수정 및 스토리지 최적화

### ISSUE THREAD

**Issue by hwb0218** [hwb0218/look-so-p#5]
## Description

- 판매자가 등록한 상품은 수정이 가능하다.
- 이미지가 수정된다면 기존 이미지 파일을 스토리지에서 삭제
- 상품 수정 시 새로운 이미지를 업로드하면, 기존에 저장된 이미지는 Cloud Storage에서 자동으로 삭제되도록 처리(스토리지 최적화)

</br>

## To-do
- [x] 등록 상품 수정 UI
- [x] 등록 이미지 수정 
- [x] 기존 이미지 스토리지에서 제거

</br>

## 레퍼런스

</br>
