### ISSUE TITLE
[FEAT] 상품 CRUD - 메인 랜딩 페이지

### ISSUE THREAD

**Issue by hwb0218** [hwb0218/look-so-p#8]
## Description

상품 CRUD - 메인 랜딩 페이지 UI, 라우팅 

</br>

## To-do

- [x]  카테고리별 상품들을 4개씩 보여주는 페이지를 설계해주세요.
- [x]  각 카테고리 옆에는 “더보기” 버튼을 배치하여, 사용자가 해당 카테고리의 상품 페이지로 이동할 수 있게 합니다.
- [x]  각 상품에는 제품명, 사진, 가격, 카테고리 정보를 표시합니다.
- [x]  제품 사진이 여러 장일 경우, 캐러셀(carousel) 기능을 통해 여러 사진을 볼 수 있게 합니다.

</br>

## 레퍼런스

</br>
